import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Flexhire Code Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-100">
        <main className="h-screen">
          <div className="flex justify-center items-center">
            <div className="text-center">
              <h1 className="text-6xl font-bold my-8">Flexhire Code Test</h1>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}